---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: ingress-nginx
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    version: 4.2.5
    name: ingress-nginx
  values:
    replicaCount: 1
    controller:
      metrics:
        enabled: true