---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mongodb-v4
  namespace: mongodb-v4
spec:
  releaseName: mongodb-v4
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: mongodb
    version: 10.30.12
  values:
    replicaCount: 3
    # Use in prod only
    nodeSelector: {
      tier: "db"
    }
    port: 27017
    replicaSetName: rs0
    architecture: replicaset
    auth:
      enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: false
        namespace: monitoring
      prometheusRule:
        enabled: false
    resources:
      limits:
        cpu: 2
      requests:
        cpu: 0.5
        memory: 0.5Gi
    extraFlags:
      - "--wiredTigerCacheSizeGB=2"
    persistence:
      enabled: true
      size: 50Gi
      storageClass: "standard"
    readinessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 2
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
    livenessProbe:
      initialDelaySeconds: 50
      timeoutSeconds: 5
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      